/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerMaintenance;
import java.util.regex.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author: Khiew Choon Hong
 */
public class RegisterNewCustomerFrame extends javax.swing.JFrame {

    private List<RegisterC> customerList = new ArrayList<RegisterC>();
    /**
     * Creates new form RegisterNewCustomerFrame
     */
    public RegisterNewCustomerFrame() {
        initComponents();
        assignID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnDisplayInfo = new javax.swing.JButton();
        jtfID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jtfName = new javax.swing.JTextField();
        jtfIC = new javax.swing.JTextField();
        jtfContactNo = new javax.swing.JTextField();
        jtfCompanyName = new javax.swing.JTextField();
        jtfEmailAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMailingAddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        nlab = new javax.swing.JLabel();
        iclab = new javax.swing.JLabel();
        cnlab = new javax.swing.JLabel();
        comlab = new javax.swing.JLabel();
        elab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Gender:");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumer", "Corporate Customer" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Status:");

        btnDisplayInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDisplayInfo.setText("Display Info");
        btnDisplayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayInfoActionPerformed(evt);
            }
        });

        jtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDActionPerformed(evt);
            }
        });
        jtfID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIDKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNameKeyReleased(evt);
            }
        });

        jtfIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfICActionPerformed(evt);
            }
        });
        jtfIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfICKeyReleased(evt);
            }
        });

        jtfContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContactNoActionPerformed(evt);
            }
        });
        jtfContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfContactNoKeyReleased(evt);
            }
        });

        jtfCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyNameActionPerformed(evt);
            }
        });
        jtfCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCompanyNameKeyReleased(evt);
            }
        });

        jtfEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailAddressActionPerformed(evt);
            }
        });
        jtfEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEmailAddressKeyReleased(evt);
            }
        });

        txtAreaMailingAddress.setColumns(20);
        txtAreaMailingAddress.setRows(5);
        txtAreaMailingAddress.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtAreaMailingAddressAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtAreaMailingAddress);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Customer Registration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("IC:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact Number:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Company Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email Address:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mailing Address:");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });

        nlab.setForeground(new java.awt.Color(255, 0, 0));

        iclab.setForeground(new java.awt.Color(255, 0, 0));

        cnlab.setForeground(new java.awt.Color(255, 0, 0));

        comlab.setForeground(new java.awt.Color(255, 0, 0));

        elab.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDisplayInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfIC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jtfEmailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCompanyName, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nlab)
                            .addComponent(iclab)
                            .addComponent(cnlab)
                            .addComponent(comlab)
                            .addComponent(elab)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nlab)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iclab)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnlab)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elab))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplayInfo)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:

        //Get selected value from combobox
        /*String status = jComboBoxStatus.getSelectedItem().toString();
        RegisterC rc = new RegisterC(status);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jComboBoxStatus.setSelectedItem("");
        jComboBoxStatus.grabFocus();*/
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void btnDisplayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, formatList());
    }//GEN-LAST:event_btnDisplayInfoActionPerformed

    private void jtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDActionPerformed

    private void assignID()
    {
        jtfID.setText("" + RegisterC.getNextID());
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = jtfName.getText();
        String ic = jtfIC.getText();
        int contactNumber = Integer.parseInt(jtfContactNo.getText());
        String companyName = jtfCompanyName.getText();
        String emailAddress = jtfEmailAddress.getText();
        String mailingAddress = txtAreaMailingAddress.getText();
        String gender = jComboBoxGender.getSelectedItem().toString();
        String status = jComboBoxStatus.getSelectedItem().toString();
        //String[] gender = {"Male", "Female"};
        //String[] status = {"Consumer", "Corporate Customer"};
        RegisterC rc = new RegisterC(name, ic, contactNumber, companyName, emailAddress, mailingAddress, gender, status);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jtfName.setText("");
        jtfName.grabFocus();
        jtfIC.setText("");
        jtfIC.grabFocus();
        jtfContactNo.setText("");
        jtfContactNo.grabFocus();
        jtfCompanyName.setText("");
        jtfCompanyName.grabFocus();
        jtfEmailAddress.setText("");
        jtfEmailAddress.grabFocus();
        txtAreaMailingAddress.setText("");
        txtAreaMailingAddress.grabFocus();
        jComboBoxGender.setSelectedItem("");
        jComboBoxGender.grabFocus();
        jComboBoxStatus.setSelectedItem("");
        jComboBoxStatus.grabFocus();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
        /*String name = jtfName.getText();
        RegisterC rc = new RegisterC(name);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        // jtaResult.setText("Runner List: \n" + formatList(runnerList));
        jtfName.setText("");
        jtfName.grabFocus();*/
    }//GEN-LAST:event_jtfNameActionPerformed

    private void jtfICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfICActionPerformed
        // TODO add your handling code here:
        /*String strIC = jtfIC.getText();
        int ic = Integer.parseInt(strIC);
        RegisterC rc = new RegisterC(ic);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jtfIC.setText("");
        jtfIC.grabFocus();*/
    }//GEN-LAST:event_jtfICActionPerformed

    private void jtfContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContactNoActionPerformed
        // TODO add your handling code here:
        /*String strCN = jtfIC.getText();
        int contactNumber = Integer.parseInt(strCN);
        RegisterC rc = new RegisterC(contactNumber);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jtfContactNo.setText("");
        jtfContactNo.grabFocus();*/
    }//GEN-LAST:event_jtfContactNoActionPerformed

    private void jtfCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyNameActionPerformed
        // TODO add your handling code here:
        /*String companyName = jtfCompanyName.getText();
        RegisterC rc = new RegisterC(companyName);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jtfCompanyName.setText("");
        jtfCompanyName.grabFocus();*/
    }//GEN-LAST:event_jtfCompanyNameActionPerformed

    private void jtfEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailAddressActionPerformed
        // TODO add your handling code here:
        /*String emailAddress = jtfEmailAddress.getText();
        RegisterC rc = new RegisterC(emailAddress);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jtfEmailAddress.setText("");
        jtfEmailAddress.grabFocus();*/
    }//GEN-LAST:event_jtfEmailAddressActionPerformed

    private void txtAreaMailingAddressAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtAreaMailingAddressAncestorAdded
        // TODO add your handling code here:
        /*String mailingAddress = txtAreaMailingAddress.getText();
        RegisterC rc = new RegisterC(mailingAddress);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        txtAreaMailingAddress.setText("");
        txtAreaMailingAddress.grabFocus();*/
    }//GEN-LAST:event_txtAreaMailingAddressAncestorAdded

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:

        //Get selected value from combobox
        /*String gender = jComboBoxGender.getSelectedItem().toString();
        RegisterC rc = new RegisterC(gender);
        customerList.add(rc);
        jtfID.setText("" + RegisterC.getNextID());
        jComboBoxGender.setSelectedItem("");
        jComboBoxGender.grabFocus();*/
    }//GEN-LAST:event_jComboBoxGenderActionPerformed

    private void jtfIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIDKeyReleased
        // TODO add your handling code here:      
    }//GEN-LAST:event_jtfIDKeyReleased

    private void jtfNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtfName.getText());
        if(!match.matches())
        {
            nlab.setText("Naming cannot spacing!");
        }
        else
        {
            nlab.setText(null);
        }
    }//GEN-LAST:event_jtfNameKeyReleased

    private void jtfEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailAddressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtfEmailAddress.getText());
        if(!match.matches())
        {
            elab.setText("Email Address is incorrect!");
        }
        else
        {
            elab.setText(null);
        }
    }//GEN-LAST:event_jtfEmailAddressKeyReleased

    private void jtfContactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactNoKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,12}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtfContactNo.getText());
        if(!match.matches())
        {
            cnlab.setText("Contact Number is incorrect!");
        }
        else
        {
            cnlab.setText(null);
        }
    }//GEN-LAST:event_jtfContactNoKeyReleased

    private void jtfICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfICKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^\\d{6}\\-\\d{2}\\-\\d{4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtfIC.getText());
        if(!match.matches())
        {
            iclab.setText("IC Number is incorrect!");
        }
        else
        {
            iclab.setText(null);
        }
    }//GEN-LAST:event_jtfICKeyReleased

    private void jtfCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtfCompanyName.getText());
        if(!match.matches())
        {
            comlab.setText("Specify company name or none!");
        }
        else
        {
            comlab.setText(null);
        }
    }//GEN-LAST:event_jtfCompanyNameKeyReleased

    public String formatList() {
        String outputStr = "";
        for (int i = 0; i < customerList.size(); ++i) {
            outputStr += (i + 1) + ". " + customerList.get(i);
        }
        return outputStr;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNewCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNewCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNewCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNewCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNewCustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayInfo;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel cnlab;
    private javax.swing.JLabel comlab;
    private javax.swing.JLabel elab;
    private javax.swing.JLabel iclab;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfCompanyName;
    private javax.swing.JTextField jtfContactNo;
    private javax.swing.JTextField jtfEmailAddress;
    private javax.swing.JTextField jtfIC;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfName;
    private javax.swing.JLabel nlab;
    private javax.swing.JTextArea txtAreaMailingAddress;
    // End of variables declaration//GEN-END:variables
}