/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agileassignment;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JeffryWong
 */
public class AddOrder1 extends javax.swing.JFrame {
    public DefaultTableModel dm;
    /**
     * Creates new form AddOrder1
     */
    public AddOrder1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup_CustType = new javax.swing.ButtonGroup();
        ButtonGroup_PaymentMethod = new javax.swing.ButtonGroup();
        ButtonGroup_DeliveryMethod = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        TextField_Price3 = new javax.swing.JTextField();
        TextField_Price4 = new javax.swing.JTextField();
        Label_ItemName = new javax.swing.JLabel();
        Label_Price = new javax.swing.JLabel();
        TextField_Quan1 = new javax.swing.JTextField();
        Label_Name = new javax.swing.JLabel();
        TextField_Quan2 = new javax.swing.JTextField();
        TextField_Name = new javax.swing.JTextField();
        TextField_Quan3 = new javax.swing.JTextField();
        TextField_Quan4 = new javax.swing.JTextField();
        Label_QuanAvai = new javax.swing.JLabel();
        Spinner_Item1 = new javax.swing.JSpinner();
        Spinner_Item2 = new javax.swing.JSpinner();
        Label_Date = new javax.swing.JLabel();
        Spinner_Item3 = new javax.swing.JSpinner();
        Label_PaymentMethod = new javax.swing.JLabel();
        Spinner_Item4 = new javax.swing.JSpinner();
        Radio_Cash = new javax.swing.JRadioButton();
        TextField_TPrice1 = new javax.swing.JTextField();
        Radio_Credit = new javax.swing.JRadioButton();
        Label_TotalPrice = new javax.swing.JLabel();
        TextField_TPrice2 = new javax.swing.JTextField();
        ComboBox_Item1 = new javax.swing.JComboBox<>();
        TextField_TPrice3 = new javax.swing.JTextField();
        ComboBox_Item2 = new javax.swing.JComboBox<>();
        TextField_TPrice4 = new javax.swing.JTextField();
        ComboBox_Item3 = new javax.swing.JComboBox<>();
        ComboBox_Item4 = new javax.swing.JComboBox<>();
        Label_CustType = new javax.swing.JLabel();
        Radio_Consumer = new javax.swing.JRadioButton();
        Radio_Corporate = new javax.swing.JRadioButton();
        Label_DeliveryMethod = new javax.swing.JLabel();
        Radio_Pickup = new javax.swing.JRadioButton();
        Radio_Delivery = new javax.swing.JRadioButton();
        Label_Address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Address = new javax.swing.JTextArea();
        TextField_TotalPrice = new javax.swing.JTextField();
        Label_OverallTotal = new javax.swing.JLabel();
        TextField_Price1 = new javax.swing.JTextField();
        Button_Add = new javax.swing.JButton();
        TextField_Price2 = new javax.swing.JTextField();
        DateChooser_Date = new com.toedter.calendar.JDateChooser();
        Button_Add1 = new javax.swing.JButton();
        Button_Add2 = new javax.swing.JButton();
        Button_Add3 = new javax.swing.JButton();
        Button_Add4 = new javax.swing.JButton();
        ComboBox_CorporateName = new javax.swing.JComboBox<>();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField_Price3.setEditable(false);

        TextField_Price4.setEditable(false);
        TextField_Price4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Price4ActionPerformed(evt);
            }
        });

        Label_ItemName.setText("Product");

        Label_Price.setText("Price per pc");

        TextField_Quan1.setEditable(false);

        Label_Name.setText("Name :");

        TextField_Quan2.setEditable(false);

        TextField_Quan3.setEditable(false);

        TextField_Quan4.setEditable(false);

        Label_QuanAvai.setText("Stock");

        Spinner_Item1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        Spinner_Item1.setToolTipText("");
        Spinner_Item1.setFocusable(false);
        Spinner_Item1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_Item1StateChanged(evt);
            }
        });

        Spinner_Item2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        Spinner_Item2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_Item2StateChanged(evt);
            }
        });

        Label_Date.setText("Date     :");

        Spinner_Item3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        Spinner_Item3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_Item3StateChanged(evt);
            }
        });

        Label_PaymentMethod.setText("Payment Method :");
        Label_PaymentMethod.setVisible(true);

        Spinner_Item4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        Spinner_Item4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_Item4StateChanged(evt);
            }
        });

        ButtonGroup_PaymentMethod.add(Radio_Cash);
        Radio_Cash.setSelected(true);
        Radio_Cash.setText("Cash");

        TextField_TPrice1.setEditable(false);

        ButtonGroup_PaymentMethod.add(Radio_Credit);
        Radio_Credit.setText("Credit");
        Radio_Credit.setEnabled(false);

        Label_TotalPrice.setText("Total");

        TextField_TPrice2.setEditable(false);

        ComboBox_Item1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_Item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_Item1MouseClicked(evt);
            }
        });
        ComboBox_Item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Item1ActionPerformed(evt);
            }
        });

        TextField_TPrice3.setEditable(false);

        ComboBox_Item2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_Item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Item2ActionPerformed(evt);
            }
        });

        TextField_TPrice4.setEditable(false);

        ComboBox_Item3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_Item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Item3ActionPerformed(evt);
            }
        });

        ComboBox_Item4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_Item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Item4ActionPerformed(evt);
            }
        });

        Label_CustType.setText("Customer Type :");

        ButtonGroup_CustType.add(Radio_Consumer);
        Radio_Consumer.setSelected(true);
        Radio_Consumer.setText("Consumer");
        Radio_Consumer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Radio_ConsumerStateChanged(evt);
            }
        });
        Radio_Consumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_ConsumerActionPerformed(evt);
            }
        });

        ButtonGroup_CustType.add(Radio_Corporate);
        Radio_Corporate.setText("Corporate");
        Radio_Corporate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Radio_CorporateStateChanged(evt);
            }
        });
        Radio_Corporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_CorporateActionPerformed(evt);
            }
        });

        Label_DeliveryMethod.setText("Pickup/Delivery :");

        ButtonGroup_DeliveryMethod.add(Radio_Pickup);
        Radio_Pickup.setSelected(true);
        Radio_Pickup.setText("Pickup");
        Radio_Pickup.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Radio_PickupStateChanged(evt);
            }
        });

        ButtonGroup_DeliveryMethod.add(Radio_Delivery);
        Radio_Delivery.setText("Delivery");
        Radio_Delivery.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Radio_DeliveryStateChanged(evt);
            }
        });
        Radio_Delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_DeliveryActionPerformed(evt);
            }
        });

        Label_Address.setText("Address :");

        TextArea_Address.setColumns(20);
        TextArea_Address.setRows(5);
        jScrollPane1.setViewportView(TextArea_Address);

        TextField_TotalPrice.setEditable(false);
        TextField_TotalPrice.setText("0");

        Label_OverallTotal.setText("Subtotal");

        TextField_Price1.setEditable(false);

        Button_Add.setText("Add Order");
        Button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddActionPerformed(evt);
            }
        });

        TextField_Price2.setEditable(false);

        Button_Add1.setText("Add");
        Button_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add1ActionPerformed(evt);
            }
        });

        Button_Add2.setText("Add");
        Button_Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add2ActionPerformed(evt);
            }
        });

        Button_Add3.setText("Add");
        Button_Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add3ActionPerformed(evt);
            }
        });

        Button_Add4.setText("Add");
        Button_Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add4ActionPerformed(evt);
            }
        });

        ComboBox_CorporateName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_CorporateName.setEnabled(false);
        ComboBox_CorporateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CorporateNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Label_PaymentMethod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Radio_Cash)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Radio_Credit))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(ComboBox_Item4, javax.swing.GroupLayout.Alignment.LEADING, 0, 122, Short.MAX_VALUE)
                                                .addComponent(ComboBox_Item3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ComboBox_Item2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(Label_ItemName)
                                            .addComponent(ComboBox_Item1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Label_Price)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(TextField_Price1)
                                            .addComponent(TextField_Price2)
                                            .addComponent(TextField_Price3)
                                            .addComponent(TextField_Price4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_Quan4)
                                    .addComponent(TextField_Quan3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextField_Quan2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextField_Quan1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label_QuanAvai, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Spinner_Item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Spinner_Item2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Spinner_Item3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spinner_Item4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Label_OverallTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextField_TPrice4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_TPrice3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_TPrice2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_TotalPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_TPrice1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_TotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Add2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Add3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Add4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_CustType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Radio_Consumer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_DeliveryMethod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Radio_Pickup)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radio_Delivery)
                            .addComponent(Radio_Corporate)))
                    .addComponent(Button_Add)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateChooser_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_CorporateName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CustType)
                    .addComponent(Radio_Consumer)
                    .addComponent(Radio_Corporate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DeliveryMethod)
                    .addComponent(Radio_Pickup)
                    .addComponent(Radio_Delivery))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Name)
                    .addComponent(TextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_CorporateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Address)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Date)
                    .addComponent(DateChooser_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_PaymentMethod)
                    .addComponent(Radio_Cash)
                    .addComponent(Radio_Credit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ItemName)
                    .addComponent(Label_Price)
                    .addComponent(Label_QuanAvai)
                    .addComponent(Label_TotalPrice))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Quan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_Item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_TPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Add1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Quan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_Item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_TPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Add2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Quan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_Item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_TPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Add3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Quan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_Item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_TPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Add4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_OverallTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Add)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_Price4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Price4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Price4ActionPerformed

    private void Radio_ConsumerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Radio_ConsumerStateChanged
        if (Radio_Consumer.isSelected()) {
            Radio_Credit.setEnabled(false);
            TextField_Name.setEnabled(true);
            ComboBox_CorporateName.setEnabled(false);
        }
    }//GEN-LAST:event_Radio_ConsumerStateChanged

    private void Radio_CorporateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Radio_CorporateStateChanged
        if (Radio_Corporate.isSelected()) {
            Radio_Credit.setEnabled(true);
            TextField_Name.setEnabled(false);
            ComboBox_CorporateName.setEnabled(true);
        }
    }//GEN-LAST:event_Radio_CorporateStateChanged

    private void Radio_CorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_CorporateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_CorporateActionPerformed

    private void Radio_PickupStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Radio_PickupStateChanged
        if (Radio_Pickup.isSelected()) {
            TextArea_Address.setEnabled(false);
            DateChooser_Date.setEnabled(true);
        }
    }//GEN-LAST:event_Radio_PickupStateChanged

    private void Radio_DeliveryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Radio_DeliveryStateChanged
        if (Radio_Delivery.isSelected()) {
            DateChooser_Date.setEnabled(false);
            TextArea_Address.setEnabled(true);
        }
    }//GEN-LAST:event_Radio_DeliveryStateChanged

    private void Radio_DeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_DeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_DeliveryActionPerformed

    private void Button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddActionPerformed
//        dm = (DefaultTableModel) ViewOrder.Table_Orders.getModel();
//        int TotalPrice = Integer.parseInt(TextField_TotalPrice.getText());
//        int 
        try {
            if (Radio_Delivery.isSelected()) {
                CODList codList = new CODList();
                codList.setCustType(ButtonGroup_CustType.getSelection().toString());
                codList.setName(TextField_Name.getText());
                codList.setAddress(TextArea_Address.getText());
                codList.setPaymentMethod(ButtonGroup_PaymentMethod.getSelection().toString());
                codList.setItemSelected1((String) ComboBox_Item1.getSelectedItem());
                codList.setItemSelected2((String) ComboBox_Item2.getSelectedItem());
                codList.setItemSelected3((String) ComboBox_Item3.getSelectedItem());
                codList.setItemSelected4((String) ComboBox_Item4.getSelectedItem());
                codList.setItemQuan1((Integer) Spinner_Item1.getValue());
                codList.setItemQuan2((Integer) Spinner_Item2.getValue());
                codList.setItemQuan3((Integer) Spinner_Item3.getValue());
                codList.setItemQuan4((Integer) Spinner_Item4.getValue());
                codList.setItemTPrice1(Double.parseDouble(TextField_TPrice1.getText()));
                codList.setItemTPrice2(Double.parseDouble(TextField_TPrice2.getText()));
                codList.setItemTPrice3(Double.parseDouble(TextField_TPrice3.getText()));
                codList.setItemTPrice4(Double.parseDouble(TextField_TPrice4.getText()));
                codList.setTotalPrice(Double.parseDouble(TextField_TotalPrice.getText()));
                JOptionPane.showMessageDialog(this, "Order Added Successfully.", "Order Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                PickupList pickupList = new PickupList();
                Calendar DateDay = Calendar.getInstance();
                int Day = DateChooser_Date.getCalendar().get(Calendar.DAY_OF_MONTH);
                int Month = DateChooser_Date.getCalendar().get(Calendar.MONTH);
                int Year = DateChooser_Date.getCalendar().get(Calendar.YEAR);
                DateDay.set(Year, Month, Day);
                pickupList.setCustType(ButtonGroup_CustType.getSelection().toString());
                pickupList.setName(TextField_Name.getText());
                pickupList.setPickupDate(DateDay);
                pickupList.setPaymentMethod(ButtonGroup_PaymentMethod.getSelection().toString());
                pickupList.setItemSelected1((String) ComboBox_Item1.getSelectedItem());
                pickupList.setItemSelected2((String) ComboBox_Item2.getSelectedItem());
                pickupList.setItemSelected3((String) ComboBox_Item3.getSelectedItem());
                pickupList.setItemSelected4((String) ComboBox_Item4.getSelectedItem());
                pickupList.setItemQuan1((Integer) Spinner_Item1.getValue());
                pickupList.setItemQuan2((Integer) Spinner_Item2.getValue());
                pickupList.setItemQuan3((Integer) Spinner_Item3.getValue());
                pickupList.setItemQuan4((Integer) Spinner_Item4.getValue());
                pickupList.setItemTPrice1(Double.parseDouble(TextField_TPrice1.getText()));
                pickupList.setItemTPrice2(Double.parseDouble(TextField_TPrice2.getText()));
                pickupList.setItemTPrice3(Double.parseDouble(TextField_TPrice3.getText()));
                pickupList.setItemTPrice4(Double.parseDouble(TextField_TPrice4.getText()));
                pickupList.setTotalPrice(Double.parseDouble(TextField_TotalPrice.getText()));
                JOptionPane.showMessageDialog(this, "Order Added Successfully.", "Order Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error details caused adding error.", "Error details caused adding error.", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Button_AddActionPerformed

    private void ComboBox_Item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Item1ActionPerformed
        String ItemSelection = (String) ComboBox_Item1.getSelectedItem();
        for (int i = 0; i < OrderFunctions.flowerList.size(); i++) {
            ComboBox_Item1.addItem(OrderFunctions.flowerList.get(i).getProductName());
            if (OrderFunctions.flowerList.get(i).getProductName().equalsIgnoreCase(ItemSelection)) {
                TextField_Price1.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductAmount()));
                TextField_Quan1.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductQuantity()));
            }
        }
    }//GEN-LAST:event_ComboBox_Item1ActionPerformed

    private void ComboBox_Item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_Item1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_Item1MouseClicked

    private void Spinner_Item4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_Item4StateChanged

    }//GEN-LAST:event_Spinner_Item4StateChanged

    private void Spinner_Item3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_Item3StateChanged

    }//GEN-LAST:event_Spinner_Item3StateChanged

    private void Spinner_Item2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_Item2StateChanged

    }//GEN-LAST:event_Spinner_Item2StateChanged

    private void Spinner_Item1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_Item1StateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_Spinner_Item1StateChanged

    private void Button_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add1ActionPerformed

        int AmountProd1 = (Integer) Spinner_Item1.getValue();
        double PerPrice1 = Double.parseDouble(TextField_Price1.getText());
        double TPrice1 = AmountProd1 * PerPrice1;
        double Subtotal = Double.parseDouble(TextField_TotalPrice.getText());
        Subtotal += TPrice1;
        String TPrice1s = String.valueOf(TPrice1);
        TextField_TPrice1.setText(TPrice1s);
        TextField_TotalPrice.setText(String.valueOf(Subtotal));
        Button_Add1.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Item Added Successfully.", "Item Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Button_Add1ActionPerformed

    private void Button_Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add2ActionPerformed
        int AmountProd2 = (Integer) Spinner_Item2.getValue();
        double PerPrice2 = Double.parseDouble(TextField_Price2.getText());
        double TPrice2 = AmountProd2 * PerPrice2;
        double Subtotal = Double.parseDouble(TextField_TotalPrice.getText());
        Subtotal += TPrice2;
        String TPrice2s = String.valueOf(TPrice2);
        TextField_TPrice2.setText(TPrice2s);
        TextField_TotalPrice.setText(String.valueOf(Subtotal));
        Button_Add2.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Item Added Successfully.", "Item Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Button_Add2ActionPerformed

    private void Button_Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add3ActionPerformed
        int AmountProd3 = (Integer) Spinner_Item3.getValue();
        double PerPrice3 = Double.parseDouble(TextField_Price3.getText());
        double TPrice3 = AmountProd3 * PerPrice3;
        double Subtotal = Double.parseDouble(TextField_TotalPrice.getText());
        Subtotal += TPrice3;
        String TPrice3s = String.valueOf(TPrice3);
        TextField_TPrice3.setText(TPrice3s);
        TextField_TotalPrice.setText(String.valueOf(Subtotal));
        Button_Add3.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Item Added Successfully.", "Item Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Button_Add3ActionPerformed

    private void Button_Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add4ActionPerformed
        int AmountProd4 = (Integer) Spinner_Item4.getValue();
        double PerPrice4 = Double.parseDouble(TextField_Price4.getText());
        double TPrice4 = AmountProd4 * PerPrice4;
        double Subtotal = Double.parseDouble(TextField_TotalPrice.getText());
        Subtotal += TPrice4;
        String TPrice4s = String.valueOf(TPrice4);
        TextField_TPrice4.setText(TPrice4s);
        TextField_TotalPrice.setText(String.valueOf(Subtotal));
        Button_Add4.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Item Added Successfully.", "Item Added Successfully.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Button_Add4ActionPerformed

    private void ComboBox_Item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Item2ActionPerformed
        String ItemSelection = (String) ComboBox_Item2.getSelectedItem();
        for (int i = 0; i < OrderFunctions.flowerList.size(); i++) {
            ComboBox_Item2.addItem(OrderFunctions.flowerList.get(i).getProductName());
            if (OrderFunctions.flowerList.get(i).getProductName().equalsIgnoreCase(ItemSelection)) {
                TextField_Price2.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductAmount()));
                TextField_Quan2.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductQuantity()));
            }
        }
    }//GEN-LAST:event_ComboBox_Item2ActionPerformed

    private void ComboBox_Item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Item3ActionPerformed
        String ItemSelection = (String) ComboBox_Item3.getSelectedItem();
        for (int i = 0; i < OrderFunctions.flowerList.size(); i++) {
            ComboBox_Item3.addItem(OrderFunctions.flowerList.get(i).getProductName());
            if (OrderFunctions.flowerList.get(i).getProductName().equalsIgnoreCase(ItemSelection)) {
                TextField_Price3.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductAmount()));
                TextField_Quan3.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductQuantity()));
            }
        }
    }//GEN-LAST:event_ComboBox_Item3ActionPerformed

    private void ComboBox_Item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Item4ActionPerformed
        String ItemSelection = (String) ComboBox_Item4.getSelectedItem();
        for (int i = 0; i < OrderFunctions.flowerList.size(); i++) {
            ComboBox_Item4.addItem(OrderFunctions.flowerList.get(i).getProductName());
            if (OrderFunctions.flowerList.get(i).getProductName().equalsIgnoreCase(ItemSelection)) {
                TextField_Price4.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductAmount()));
                TextField_Quan4.setText(String.valueOf(OrderFunctions.flowerList.get(i).getProductQuantity()));
            }
        }
    }//GEN-LAST:event_ComboBox_Item4ActionPerformed

    private void ComboBox_CorporateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CorporateNameActionPerformed

        for (int i = 0; i < OrderFunctions.customerList.size(); i++) {
            if (OrderFunctions.customerList.get(i).getStatus().equalsIgnoreCase("Corporate")) {
                ComboBox_CorporateName.addItem(OrderFunctions.customerList.get(i).getName());
                TextField_Name.setText(String.valueOf(OrderFunctions.customerList.get(i).getName()));
            }    }//GEN-LAST:event_ComboBox_CorporateNameActionPerformed
    }
    private void Radio_ConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_ConsumerActionPerformed

    }//GEN-LAST:event_Radio_ConsumerActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup_CustType;
    private javax.swing.ButtonGroup ButtonGroup_DeliveryMethod;
    private javax.swing.ButtonGroup ButtonGroup_PaymentMethod;
    private javax.swing.JButton Button_Add;
    private javax.swing.JButton Button_Add1;
    private javax.swing.JButton Button_Add2;
    private javax.swing.JButton Button_Add3;
    private javax.swing.JButton Button_Add4;
    private javax.swing.JComboBox<String> ComboBox_CorporateName;
    private javax.swing.JComboBox<String> ComboBox_Item1;
    private javax.swing.JComboBox<String> ComboBox_Item2;
    private javax.swing.JComboBox<String> ComboBox_Item3;
    private javax.swing.JComboBox<String> ComboBox_Item4;
    private com.toedter.calendar.JDateChooser DateChooser_Date;
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_CustType;
    private javax.swing.JLabel Label_Date;
    private javax.swing.JLabel Label_DeliveryMethod;
    private javax.swing.JLabel Label_ItemName;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_OverallTotal;
    private javax.swing.JLabel Label_PaymentMethod;
    private javax.swing.JLabel Label_Price;
    private javax.swing.JLabel Label_QuanAvai;
    private javax.swing.JLabel Label_TotalPrice;
    private javax.swing.JRadioButton Radio_Cash;
    private javax.swing.JRadioButton Radio_Consumer;
    private javax.swing.JRadioButton Radio_Corporate;
    private javax.swing.JRadioButton Radio_Credit;
    private javax.swing.JRadioButton Radio_Delivery;
    private javax.swing.JRadioButton Radio_Pickup;
    private javax.swing.JSpinner Spinner_Item1;
    private javax.swing.JSpinner Spinner_Item2;
    private javax.swing.JSpinner Spinner_Item3;
    private javax.swing.JSpinner Spinner_Item4;
    private javax.swing.JTextArea TextArea_Address;
    private javax.swing.JTextField TextField_Name;
    private javax.swing.JTextField TextField_Price1;
    private javax.swing.JTextField TextField_Price2;
    private javax.swing.JTextField TextField_Price3;
    private javax.swing.JTextField TextField_Price4;
    private javax.swing.JTextField TextField_Quan1;
    private javax.swing.JTextField TextField_Quan2;
    private javax.swing.JTextField TextField_Quan3;
    private javax.swing.JTextField TextField_Quan4;
    private javax.swing.JTextField TextField_TPrice1;
    private javax.swing.JTextField TextField_TPrice2;
    private javax.swing.JTextField TextField_TPrice3;
    private javax.swing.JTextField TextField_TPrice4;
    private javax.swing.JTextField TextField_TotalPrice;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
